"""pi_agent_core: Python port of the Pi agent core.

Mirrors ``packages/agent/src`` from the TypeScript Pi agent. Exposes the
core types, the stateful :class:`Agent`, and the low-level agent loop.
"""

from __future__ import annotations

from .agent import Agent, AgentOptions, create_mutable_agent_state
from .agent_loop import run_agent_loop, run_agent_loop_continue
from .stream_fn import get_default_stream_fn, set_default_stream_fn
from .types import (
    EMPTY_USAGE,
    AfterToolCallContext,
    AfterToolCallFn,
    AfterToolCallResult,
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentEventSink,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentMessage,
    AgentStartEvent,
    AgentState,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    AgentToolUpdateCallback,
    AssistantMessageEventStream,
    BeforeToolCallContext,
    BeforeToolCallFn,
    BeforeToolCallResult,
    ConvertToLlmFn,
    GetApiKeyFn,
    GetMessagesFn,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    PrepareNextTurnContext,
    PrepareNextTurnFn,
    QueueMode,
    ShouldStopAfterTurnContext,
    ShouldStopAfterTurnFn,
    StreamFn,
    ThinkingLevel,
    ToolExecutionEndEvent,
    ToolExecutionMode,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TransformContextFn,
    TurnEndEvent,
    TurnStartEvent,
)

__all__ = [
    "EMPTY_USAGE",
    "AfterToolCallContext",
    "AfterToolCallFn",
    "AfterToolCallResult",
    "Agent",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentEventSink",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentOptions",
    "AgentStartEvent",
    "AgentState",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "AssistantMessageEventStream",
    "BeforeToolCallContext",
    "BeforeToolCallFn",
    "BeforeToolCallResult",
    "ConvertToLlmFn",
    "GetApiKeyFn",
    "GetMessagesFn",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "PrepareNextTurnContext",
    "PrepareNextTurnFn",
    "QueueMode",
    "ShouldStopAfterTurnContext",
    "ShouldStopAfterTurnFn",
    "StreamFn",
    "ThinkingLevel",
    "ToolExecutionEndEvent",
    "ToolExecutionMode",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TransformContextFn",
    "TurnEndEvent",
    "TurnStartEvent",
    "create_mutable_agent_state",
    "get_default_stream_fn",
    "run_agent_loop",
    "run_agent_loop_continue",
    "set_default_stream_fn",
]
